### ISSUE TITLE
Rendering View Data

### ISSUE THREAD

**Issue by mavieth** [18F/analytics-reporter#134]
I am able to get well-formatted json output running the command:
./bin/analytics

When I run the web server, I receive the error 
`Error: Failed to lookup view "index" in views directory "../"
    at Function.app.render (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/application.js:516:17)
    at ServerResponse.res.render (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/response.js:900:7)
    at /home/ec2-user/apps/analytics-reporter/app/routes.js:13:11
    at Layer.handle [as handle_request] (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/layer.js:82:5)
    at /home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/index.js:312:12)
    at /home/ec2-user/apps/analytics-reporter/node_modules/express/lib/router/index.js:228:12`

Where are the views rendered?

Do you have any examples of views that I could test out?

**Comment by konklone** [comment]
So, the included web server isn't something the analytics.usa.gov team uses or supports right now. I believe it used by at least one user, @polastre, who may have some insight.

The analytics.usa.gov team uses a front-end (code at https://github.com/18F/analytics.usa.gov) that expects the output of running `./bin/analytics` to be hosted at predictable URLs. The site then has JavaScript fetch the JSON from those URLs using CORS and renders them client-side.

**Comment by polastre** [comment]
In `config.js` you need to set the path to the front end code.  The code that @konklone uses is static and has diverged (I haven't been following it). You can find front end code that has been genericized with the right templates at https://github.com/polastre/analytics.example.org

**Comment by gbinal** [comment]
Thanks, folks.  I'm going to go ahead and close this.
